Comments ::= (S | Comment | JSDocComment)*

Comment  ::= '/*' ( CommentContents | Comment | '@' )* '*/'

JSDocComment  ::= '/**' Contents TaggedContents* '*/'
Contents ::= ( Char | Trim )*
TaggedContents ::= '@' Tag Contents

<?TOKENS?>

Tag ::= [A-Za-z0-9]+

CommentContents ::=
    ( ( [^(:] | '('+ [^(:] | ':'+ [^:)] )+ | '(' ) '('* & '('
  | ( ( [^(:] | '('+ [^(:] | ':'+ [^:)] )+ | ':' ) ':'* & ':'

Char ::= [^@#x000A<]
Trim ::= #x000A ( #x0020 | #x0009 )* ':'?

S ::= ( #x0020 | #x0009 | #x000D | #x000A )+
